# Generated by Django 5.1.5 on 2025-01-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_alter_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
